### ISSUE TITLE
Poll, pipes and high cpu usage

### ISSUE THREAD

**Issue by explosion-mental** [explosion-mental/poll#1]

**Comment by explosion-mental** [comment]
I hope u don't mind testing an looking that it is actually taking high cpu usage.

**Comment by explosion-mental** [comment]
hmmm, for some reason I get a complete freeze when writing to the pipe

**Comment by TAAPArthur** [comment]
When I said dummy program, I meant like <100 hundreds. Really just the minimal amount of code needed to repo the issue. So basically just creating create the pipes, calling poll and forking/exec and reading the pipe in a loop. That's probably about a dozen. X isn't really needed. I don't really mind if X is used as one of the fds if the X specific code is isolated in another method. 

I think you are just making some classic mistakes related to the nature of pipes and poll and it may be easier to just focus on that and ignore everything else. Once you get that working, it should be trivial to plugin it back in.

If you need to simulate input/external events poll stdin and press enter to trigger an event.

But your problem sounds like what I warned about: writing to a pipe will eventually block if there is no reader

**Comment by explosion-mental** [comment]
Is [this](https://github.com/explosion-mental/dummy-poll) any better?

**Comment by TAAPArthur** [comment]
Better? yes. Ideal? No. Think it could be more [minimal](https://en.wikipedia.org/wiki/Minimal_reproducible_example). It just helps with debugging (for your and for others) when there is less unrelated stuff. 

You said this code blocks when writing? I don't see the part where you write. It looks like it would hang on reading if you wrote too much for the reasons explained above.

I'd recommend taking a step back and just confirm you can read from stdin (a single fd). Then try a pipe with a child process writing. Then try both. Then add in X. They all should be largely the same thing but it would probably be easier to debug the earlier cases than the latter. Like if you can't read stdin, you're pipe/read code is flawed while if you have some problem with X then it really could be anything.

I think the problem is what your code to clear the pipe which could be confirmed with the simplest examples (like just poll, read and maybe write so you can manually confirm the output).

```
while(poll(...)){
if
}
```

**Comment by explosion-mental** [comment]
okay okay, This should be it

**Comment by explosion-mental** [comment]
To me looks very clean and should be a good base for adding things. What are your thoughts?

**Comment by explosion-mental** [comment]
oh yeah, change repo issues

**Comment by explosion-mental** [comment]
https://github.com/explosion-mental/dummy-poll/issues/1#issue-1160182966
